name: Java CI with Gradle

env:
  PROJECT_NAME: airDnsTest
  BUCKET_NAME: githubactionaws
  CODE_DEPLOY_APP: airDnS-test
  CODE_DEPLOY_DEPLOYMENT_GROUP: springbootwithgitaction
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2 # 만약 v1이라면 with의 distribution는 생략해도 된다.
      with:
        java-version: '17'
        distribution: 'zulu'

    # 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # Build Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # DockerHub 계정 로그인
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_PASSWORD}}

    # *.jar -> Docker Image Build
    - name: Docker Image Build
      run: docker build --platform linux --build-arg DEPENDENCY=build/dependency -t ${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.PROJECT_NAME }} .

    # DockerHub's Image push
    - name: DockerHub Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/airDnsTest

    # run application
    - name: Run Application
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker kill airDnsTest
          sudo docker rm -f airDnsTest
          sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/airDnsTest
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/airDnsTest
          sudo docker run -p 8082:8082 \
                      --name airDnsTest \
                      -d ${{ secrets.DOCKERHUB_USERNAME}}/airDnsTest